server:
  port: 8761 #porta default eureka

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 1

spring:
  application:
    name: eureka-server
